version: '3'

volumes:
  bundler:
  mongodb:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached
      - bundler:/usr/local/bundle
      - node_modules:/workspace/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
