version: '3'

volumes:
  bundler:
  mongodb:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '4'

    volumes:
      - ..:/workspace:cached
      - bundler:/usr/local/bundle

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
